Personally.WebUI/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Personally.Business.Abstract;
using Personally.Entities;
using Personally.WebUI.Models;

namespace Personally.WebUI.Controllers
{
    public class AdminController : Controller
    {
        private INoteService _noteService;
        private ICategoryService _categoryService;
        public AdminController(INoteService noteService,ICategoryService categoryService)
        {
            _noteService = noteService;
            _categoryService = categoryService;

        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CreateNote()
        {
            ViewBag.Categories = _categoryService.GetAllCategories();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateNote(NoteModel model,IFormFile file,int[] categoryIds )
        {
            if(ModelState.IsValid)
            { 
            if(file!=null)
            {
                var path = Path.Combine(Directory.GetCurrentDirectory(),"wwwroot\\img", file.FileName);

                using(var stream=new FileStream(path,FileMode.Create))
                {
                    await file.CopyToAsync(stream);
                }
                var entity = new Note
                {
                    Title = model.Title,
                    Description = model.Description,
                    ImageUrl = file.FileName,
                    IsDraft = model.IsDraft,
                    Owner = model.Owner
                    
                };
                _noteService.Create(entity);
                    //_noteService.CreteNoteWithCategory(entity, categoryIds);
                
            }
                return Redirect("ListNotes");

            }
            return View(); 
        }


        public IActionResult ListNotes()
        {
            return View(new NoteListModel() {
                Notes=_noteService.GetAll()
            });
        }


        public IActionResult EditNote(int id)
        {
            var entity = _noteService.GetByIdWithCategories((int)id);

            var model = new NoteModel()
            {
                Id=entity.Id,
                Title=entity.Title,
                Description=entity.Description,
                ImageUrl=entity.ImageUrl,
                Owner=entity.Owner,
                SelectedCategories=entity.noteCategories.Select(i=>i.Category).ToList()
            };

            ViewBag.Categories = _categoryService.GetAllCategories();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditNote(NoteModel model,IFormFile file, int[] categoryIds)
        {

            if (ModelState.IsValid)
            {
                var entity = _noteService.GetById(model.Id);

                entity.ImageUrl = model.ImageUrl;
                entity.IsDraft = model.IsDraft;
                entity.Owner = model.Owner;
                entity.Title = model.Title;
                entity.Description = model.Description;

                if (file != null)
                {
                    entity.ImageUrl = file.FileName;
                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\img", file.FileName);
                    using (var stream = new FileStream(path, FileMode.Create))
                    {
                        await file.CopyToAsync(stream);
                    }
                }
                _noteService.Update(entity,categoryIds);
                            return RedirectToAction("EditNote", entity);

            }
            return RedirectToAction("EditNote", model.Id);
        }

        public IActionResult DeleteNote(int deleteNote)
        {
            var entity = _noteService.GetById(deleteNote);
            _noteService.Delete(entity);
                return Redirect("ListNotes");
        }

        public IActionResult CategoryList()
        {
            return View(new CategoryListModel() {
                Categories=_categoryService.GetAllCategories()
            }
            );
        }

        public IActionResult EditCategory(int id)
        {
            var entity = _categoryService.GetByWithNotes(id);
            return View(new CategoryModel()
            {
                Id=entity.Id,
                Title=entity.Title,
                Notes=entity.noteCategories.Select(x=>x.Note).ToList()
            });
        }
        [HttpPost]
        public IActionResult EditCategory(CategoryModel model)
        {
            var entity = _categoryService.GetById(model.Id);

            entity.Title = model.Title;
            _categoryService.Update(entity);
            return RedirectToAction("CategoryList");
        }

        public IActionResult CreateCategory()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateCategory(CategoryModel model)
        {
            var entity = new Category()
            {
                Title = model.Title
            };
            _categoryService.Create(entity);
            return RedirectToAction("CategoryList");
        }


        public IActionResult DeleteCategory(int categoryId)
        {
            var entity = _categoryService.GetById(categoryId);
            _categoryService.Delete(entity);
            return RedirectToAction("CategoryList");
        }

        [HttpPost]
        public IActionResult DeleteFromCategory(int categoryId, int noteId)
        {
            _categoryService.DeleteFromCategory(categoryId, noteId);
            return Redirect("EditCategory/"+categoryId);
        }
    }
}

Personally.WebUI/Controllers/NoteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Personally.Business.Abstract;
using Personally.Entities;
using Personally.WebUI.Models;

namespace Personally.WebUI.Controllers
{
    public class NoteController : Controller
    {
        private INoteService _noteService;
        public NoteController(INoteService noteService)
        {
            _noteService = noteService;

        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Detail(int? id)
        {
            if(id==null)
            {
                return NotFound();
            }

            Note noteDetail = _noteService.GetNoteDetail((int)id);
            if(noteDetail==null)
            {
                return NotFound();
            }


            return View(new NoteDetailModel()
            {
                Note=noteDetail,
                Categories=noteDetail.noteCategories.Select(x=>x.Category).ToList(),
                Comments=noteDetail.Comments

            });;
        }


        public IActionResult AddNote()
        {
            return View();
        }

        public IActionResult List(string category,int page=1)
        {
            const int pageSize = 2;
            return View(new NoteListModel()
            {
                 PageInfo=new PageInfo()
                 {
                     TotalItems=_noteService.GetCounByCategory(category),
                     CurrentPage=page,
                     ItemsPerPage=pageSize,
                     CurrentCategory=category
                 },

                Notes=_noteService.GetNotesByCategory(category, page,pageSize)
            });;
        }

    }
}

Personally.WebUI/ViewComponents/CategoryListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Personally.Business.Abstract;
using Personally.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Personally.WebUI.ViewComponents
{
    public class CategoryListViewComponent:ViewComponent
    {
        private ICategoryService _categoryService;
        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public IViewComponentResult Invoke()
        {
            return View(new CategoryListViewModel() {

                Categories = _categoryService.GetAllCategories()

            });           
        }
    }
}

Personally.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Home - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/css/blog-home.css" rel="stylesheet">

    <link href="~/css/bootstrap.css" rel="stylesheet">

    <!-- FontAwesome Icons core CSS -->
    <link href="~/css/font-awesome.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="~/style.css" rel="stylesheet">

    <!-- Responsive styles for this template -->
    <link href="~/css/responsive.css" rel="stylesheet">

    <!-- Colors for this template -->
    <link href="~/css/colors.css" rel="stylesheet">

    <!-- Version Garden CSS for this template -->
    <link href="~/css/version/garden.css" rel="stylesheet">
</head>

<body>
    <partial name="_navbar" />
    <div class="container">

       

            @RenderBody()



      


    </div>



    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2019</p>
        </div>

    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="~/vendor/jquery/jquery.min.js"></script>
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    @RenderSection("Scripts", false)


</body>

</html>

Personally.WebUI/Views/Shared/_categorypartial.cshtml
<div class="col-md-4">

    <!-- Search Widget -->
    <div class="card my-4">
        <h5 class="card-header">Search</h5>
        <div class="card-body">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                    <button class="btn btn-secondary" type="button">Go!</button>
                </span>
            </div>
        </div>
    </div>

    <!-- Categories Widget -->
        @await  Component.InvokeAsync("CategoryList")
    <!-- Side Widget -->
    <div class="card my-4">
        <h5 class="card-header">Side Widget</h5>
        <div class="card-body">
            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
        </div>
    </div>

</div>

Personally.WebUI/Views/Shared/_navbar.cshtml
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="#">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">
                        Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" asp-controller="Note" asp-action="List">Notlar</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Admin
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a asp-controller="Admin"
                           asp-action="ListNotes" class="dropdown-item" >Notları Listele</a>
                        <a class="dropdown-item" asp-controller="Admin" asp-action="CategoryList"> Kategori Listele</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Hakkımda</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">BilgeAdam Nbuy</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Bana Ulaş</a>
                </li>
            </ul>
        </div>
    </div>
</nav>